# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
    - come-nc
    - Altahrim
  labels:
    - "3. to review"
    - "dependencies"

# behat
- package-ecosystem: composer
  directory: "/vendor-bin/tests"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
    - come-nc
    - Altahrim
  labels:
    - "3. to review"
    - "dependencies"

# box
- package-ecosystem: composer
  directory: "/vendor-bin/box"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
    - come-nc
    - Altahrim
  labels:
    - "3. to review"
    - "dependencies"

# coding-standard
- package-ecosystem: composer
  directory: "/vendor-bin/coding-standard"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
    - come-nc
    - Altahrim
  labels:
    - "3. to review"
    - "dependencies"

# psalm
- package-ecosystem: composer
  directory: "/vendor-bin/psalm"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
    - come-nc
    - Altahrim
  labels:
    - "3. to review"
    - "dependencies"
