# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Test various integration tests

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

concurrency:
  group: updater-test-various-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-various:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.2"]

    name: test-various

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: apcu,ctype,curl,dom,fileinfo,ftp,gd,intl,json,ldap,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
          ini-file: development

      - name: Install dependencies
        run: composer i

      - name: test-user.ini
        run: make test-user.ini

  summary:
    runs-on: ubuntu-latest
    needs: test-various

    if: always()

    name: test-various-summary

    steps:
      - name: Summary status
        run: if ${{ needs.test-various.result != 'success' }}; then exit 1; fi
